name: Key Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment‌‌
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get install git zip curl openssl unzip -y

      - name: Generate Keys
        run: |
          cd $GITHUB_WORKSPACE
          sudo chmod -R 0777 ./*
          mkdir work
          mkdir out
          cd work
          git clone https://github.com/arunv2518p/vendor_droidx-priv_keys-template.git vendor/lineage-priv/keys
          cd vendor/lineage-priv/keys
          sudo bash ./gen_keys
          cd ../../../
          sudo zip -r9 keys.zip *
          cp *.zip /home/runner/work/vendor_droidx-priv_keys-template/vendor_droidx-priv_keys-template/out/

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/work/vendor_droidx-priv_keys-template/vendor_droidx-priv_keys-template/out/*
          name: Keys-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Keys
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
